from fastapi import APIRouter, UploadFile, File, Form, HTTPException
from fastapi.responses import JSONResponse
import base64
from io import BytesIO
from PIL import Image
import os
from dotenv import load_dotenv


from google import genai
from google.genai import types


router = APIRouter()


load_dotenv(os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), '.env'))


client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))


@router.post("/generate")
async def generate_design(
    image: UploadFile = File(...),
    prompt: str = Form(...)
):


    if not image:
        raise HTTPException(status_code=400, detail="No image file provided.")
    if not prompt.strip():
        raise HTTPException(status_code=400, detail="Prompt text is required.")


    try:
        image_bytes = await image.read()
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error reading image file: {str(e)}")
   
    try:
        pil_image = Image.open(BytesIO(image_bytes))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error processing the image: {str(e)}")
   


    try:
        contents = [prompt, pil_image]




        response = client.models.generate_content(
            model="gemini-2.0-flash-exp-image-generation",
            contents=contents,
            config=types.GenerateContentConfig(
                response_modalities=['Text', 'Image']
            )
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error calling Gemini API: {str(e)}")


    generated_image_base64 = None
    text_response = []
   
    try:
        for part in response.candidates[0].content.parts:
            if part.text is not None:
                text_response.append(part.text)
            elif part.inline_data is not None:
                try:
                    image_obj = Image.open(BytesIO(part.inline_data.data))
                    buffered = BytesIO()
                    image_obj.save(buffered, format="PNG")
                    generated_image_base64 = base64.b64encode(buffered.getvalue()).decode("utf-8")
                except Exception as img_error:
                    raise HTTPException(status_code=500, detail=f"Error processing generated image: {str(img_error)}")
    except Exception as proc_error:
        raise HTTPException(status_code=500, detail=f"Error processing Gemini API response: {str(proc_error)}")


    if generated_image_base64 is None:
        raise HTTPException(status_code=500, detail="No image generated by the Gemini API.")


    return JSONResponse(content={"base64_image": generated_image_base64, "text": text_response})